Repository bbolab/gaonna-backend, pull requests merged in 2021-09, with the labels that each got.

#55 Implement api spec
  api/src/main/java/com/bbolab/gaonna/api/v1/controller/CommentController.java
  api/src/main/java/com/bbolab/gaonna/api/v1/controller/MemberController.java
  api/src/main/java/com/bbolab/gaonna/api/v1/controller/MockFactoryUtil.java
  api/src/main/java/com/bbolab/gaonna/api/v1/controller/ProfileController.java
  api/src/main/java/com/bbolab/gaonna/api/v1/controller/QuestController.java
  api/src/main/java/com/bbolab/gaonna/api/v1/controller/QuestReserveController.java
  api/src/main/java/com/bbolab/gaonna/api/v1/dto/comment/CommentCreateUpdateRequestDto.java
  api/src/main/java/com/bbolab/gaonna/api/v1/dto/comment/CommentDto.java
  api/src/main/java/com/bbolab/gaonna/api/v1/dto/comment/CommentListResponseDto.java
  api/src/main/java/com/bbolab/gaonna/api/v1/dto/comment/CommentResponseDto.java
  api/src/main/java/com/bbolab/gaonna/api/v1/dto/member/MemberDto.java
  api/src/main/java/com/bbolab/gaonna/api/v1/dto/member/MemberInfoDto.java
  api/src/main/java/com/bbolab/gaonna/api/v1/dto/member/profile/ProfileCreateRequestDto.java
  api/src/main/java/com/bbolab/gaonna/api/v1/dto/member/profile/ProfileDetailDto.java
  api/src/main/java/com/bbolab/gaonna/api/v1/dto/member/profile/ProfileDetailListDto.java
  api/src/main/java/com/bbolab/gaonna/api/v1/dto/member/profile/ProfileDto.java
  api/src/main/java/com/bbolab/gaonna/api/v1/dto/quest/QuestDetailResponseDto.java
  api/src/main/java/com/bbolab/gaonna/api/v1/dto/quest/QuestListItemDto.java
  api/src/main/java/com/bbolab/gaonna/api/v1/dto/quest/QuestListResponseDto.java
  api/src/main/java/com/bbolab/gaonna/api/v1/dto/quest/QuestListResponseItemDto.java
  api/src/main/java/com/bbolab/gaonna/api/v1/dto/quest/QuestPerformerDto.java
  api/src/main/java/com/bbolab/gaonna/api/v1/dto/reserve/ReserveQuestRequestDto.java
  api/src/main/java/com/bbolab/gaonna/api/v1/dto/reserve/ReserveQuestResponseDto.java
  api/src/main/java/com/bbolab/gaonna/api/v1/dto/review/ReviewListItemDto.java
  api/src/test/java/com/bbolab/gaonna/api/controller/MockCommentControllerTest.java
  api/src/test/java/com/bbolab/gaonna/api/controller/MockQuestControllerTest.java
  api/src/test/java/com/bbolab/gaonna/api/v1/controller/MockMemberControllerTest.java
  api/src/test/java/com/bbolab/gaonna/api/v1/controller/MockProfileControllerTest.java
  api/src/test/java/com/bbolab/gaonna/api/v1/controller/MockQuestReserveControllerTest.java
Labels: enhancement, feature

#56 fix: change github credential
  Jenkins/Jenkinsfile
Labels: bug

#57 feat: add slack notification functionality
  Jenkins/Jenkinsfile
Labels: enhancement
